In [10]:
#1.Write a function to compute 5/0 and use try/except to catch the exceptions

def divideByZero():
    return 5/0

try:
    divideByZero()
except ZeroDivisionError as error:
    print("From Except divideByZero Block, Error is:",error)

From Except divideByZero Block, Error is: division by zero


In [24]:
#2.
#Implement a Python program to generate all sentences where subject is in ["Americans",
#"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
#Hint: Subject,Verb and Object should be declared in the program as shown below.
#subjects=["Americans ","Indians"]
#verbs=["play","watch"]
#objects=["Baseball","Cricket"]

class SentenceFormation:
       
    def __init__(self,subjects,verbs,objects):
        self.finalSentence = [(subject+" "+verb+" "+obj ) for subject in subjects for verb in verbs for obj in objects]   
    
    def printEachSentence(self):
        for eachSentence in self.finalSentence:
            print(eachSentence)

In [25]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

instanceOfSentenceFormation = SentenceFormation(subjects,verbs,objects)
instanceOfSentenceFormation.printEachSentence()


Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [41]:
#Task 2:
#1.Write a function so that the columns of the output matrix are powers of the input vector.
#The order of the powers is determined by the increasing boolean argument. Specifically, when
#increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
#HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

import numpy as np
X = np.array([1,2,3,4])
N=4

In [42]:
finalMatrix = np.column_stack([X**(N-i-1) for i in range(N)])
print(finalMatrix)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]
